# Generated by Django 3.2.4 on 2021-06-10 23:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField()),
                ('sub_title', models.TextField()),
                ('description', models.TextField()),
                ('created_time', models.DateTimeField(auto_now_add=True)),
                ('end_time', models.DateTimeField(null=True)),
                ('voted_token_amount', models.FloatField(default=0.0)),
                ('direction_type', models.CharField(choices=[('L', 'LONG'), ('S', 'SHORT')], default='L', help_text='방향성', max_length=2, verbose_name='방향성')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='written_article', to=settings.AUTH_USER_MODEL)),
                ('voter', models.ManyToManyField(related_name='voted_article', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
