# Generated by Django 3.2.4 on 2021-06-11 10:43

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('article', '0002_auto_20210611_1916'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='voter',
            field=models.ManyToManyField(blank=True, null=True, related_name='voted_article', to=settings.AUTH_USER_MODEL),
        ),
    ]
